config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/followings'
  # get 'relationships/followers'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  get 'search', to: 'searches#search'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    search = params[:search]
    @word = params[:word]
    if @range == 'Users'
      @user = User.search(search, @word)
    else
      @book = Book.search(search, @word)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag (:word) %>
    <%= select_tag 'range' ,options_for_select([['User', 'Users'], ['Book', 'Books']]) %>
    <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
    <%= submit_tag "検索" %>
  <% end %>
<% end %>

app/views/searches/_search_book.html.erb
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody id="book">
      <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
          <td><%= book.body %></td>
        </tr>
    </tbody>
  </table>

app/views/searches/_search_user.html.erb
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/searches/search.html.erb
<div class="container">
    <div class="d-flex align-items-center justify-content-center">
      <%= render 'searches/form' %>
    </div>
</div>

<h3><%= @range %> search for "<%= @word %>"</h3>
<!--books一覧 -->
<table class="table table-hover table-inverse">
　<% if @range == 'Books' %>
  <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
     <% @book.each do |book| %>
     <tr>
      <td>
       <%= link_to(book.user) do %>
         <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
       <% end %>
      </td>
      <td>
       <%= link_to book.title, book, class: "book_#{book.id}" %>
      </td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
  </tbody>

  <% else %>
  <!--users一覧 -->
  <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
     <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
      <td><%= user.name%></td>
      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
     </tr>
    <% end %>
   </tbody>
   <% end %>
 </table>